#  ### — это разделитель между запросами, рекомендованный в PyCharm.
# В заголовке content-type нельзя указывать JSON.
# Должно быть разделение между заголовками и телом запроса.

// ###  _______________  RESPONSES ___________________________________________________________________________

### Responses - GET - получить ВСЕ ответы на вопросы из БД
GET http://127.0.0.1:5000/responses/ HTTP/1.1
content-type: application/json

### Responses - POST - ОТПРАВИТЬ ответ на вопрос 1 в БД
POST http://127.0.0.1:5000/responses/ HTTP/1.1
content-type: application/json

# ___ Users:
# user 1: Ich Ich_123                   # user 4: Falkor 456Falkor
# user 2: Man Man_456                   # user 5: Noname 000N
# user 3: Masiya 123Masiya              # user 6: Test for Delete Anon123
# ___ Responses - VARIANTS:
# q1, user 3: Yes, but it was originally created by people. And now it has become a miracle.
# q_, user _: _

{
    "question_id": 13,
    "is_agree": false,
    "text": "",
    "user_id": 4
}

### Responses - GET - получить ответ по ID (ответ 2) из БД. Ввести эндпоинт /1.
GET http://127.0.0.1:5000/responses/2 HTTP/1.1
content-type: application/json

### Responses - DELETE - УДАЛИТЬ ответ по ID (ответ 2) из БД. Ввести эндпоинт /1.
DELETE  http://127.0.0.1:5000/responses/2 HTTP/1.1
content-type: application/json

### Responses - PUT - ИЗМЕНИТЬ ответ по ID (ответ 2) из БД. Ввести эндпоинт /2.
PUT  http://127.0.0.1:5000/responses/2 HTTP/1.1
content-type: application/json

{
    "question_id": 2,
    "is_agree": false,
    "text": "No, it is wonderful day :)"
}
